// Generated by gencpp from file robot/BeaconResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_BEACONRESPONSE_H
#define ROBOT_MESSAGE_BEACONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct BeaconResponse_
{
  typedef BeaconResponse_<ContainerAllocator> Type;

  BeaconResponse_()
    : angle_from_robot(0.0)
    , x(0.0)
    , y(0.0)
    , only_bottom(false)
    , beacon_not_found(false)
    , beacon_angle_conf(false)  {
    }
  BeaconResponse_(const ContainerAllocator& _alloc)
    : angle_from_robot(0.0)
    , x(0.0)
    , y(0.0)
    , only_bottom(false)
    , beacon_not_found(false)
    , beacon_angle_conf(false)  {
    }



   typedef float _angle_from_robot_type;
  _angle_from_robot_type angle_from_robot;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _only_bottom_type;
  _only_bottom_type only_bottom;

   typedef uint8_t _beacon_not_found_type;
  _beacon_not_found_type beacon_not_found;

   typedef uint8_t _beacon_angle_conf_type;
  _beacon_angle_conf_type beacon_angle_conf;




  typedef boost::shared_ptr< ::robot::BeaconResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::BeaconResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BeaconResponse_

typedef ::robot::BeaconResponse_<std::allocator<void> > BeaconResponse;

typedef boost::shared_ptr< ::robot::BeaconResponse > BeaconResponsePtr;
typedef boost::shared_ptr< ::robot::BeaconResponse const> BeaconResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::BeaconResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::BeaconResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::BeaconResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::BeaconResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::BeaconResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::BeaconResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::BeaconResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::BeaconResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::BeaconResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0418911b827747ed56cc16bc2cb6af6";
  }

  static const char* value(const ::robot::BeaconResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0418911b827747eULL;
  static const uint64_t static_value2 = 0xd56cc16bc2cb6af6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::BeaconResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/BeaconResponse";
  }

  static const char* value(const ::robot::BeaconResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::BeaconResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_from_robot\n\
float32 x\n\
float32 y\n\
bool only_bottom\n\
bool beacon_not_found\n\
bool beacon_angle_conf\n\
";
  }

  static const char* value(const ::robot::BeaconResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::BeaconResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_from_robot);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.only_bottom);
      stream.next(m.beacon_not_found);
      stream.next(m.beacon_angle_conf);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BeaconResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::BeaconResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::BeaconResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle_from_robot: ";
    Printer<float>::stream(s, indent + "  ", v.angle_from_robot);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "only_bottom: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.only_bottom);
    s << indent << "beacon_not_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.beacon_not_found);
    s << indent << "beacon_angle_conf: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.beacon_angle_conf);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_BEACONRESPONSE_H
