// Generated by gencpp from file robot/BeaconRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_BEACONREQUEST_H
#define ROBOT_MESSAGE_BEACONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct BeaconRequest_
{
  typedef BeaconRequest_<ContainerAllocator> Type;

  BeaconRequest_()
    : angle_from_robot(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  BeaconRequest_(const ContainerAllocator& _alloc)
    : angle_from_robot(0.0)
    , x(0.0)
    , y(0.0)  {
    }



   typedef float _angle_from_robot_type;
  _angle_from_robot_type angle_from_robot;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::robot::BeaconRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::BeaconRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BeaconRequest_

typedef ::robot::BeaconRequest_<std::allocator<void> > BeaconRequest;

typedef boost::shared_ptr< ::robot::BeaconRequest > BeaconRequestPtr;
typedef boost::shared_ptr< ::robot::BeaconRequest const> BeaconRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::BeaconRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::BeaconRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::BeaconRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::BeaconRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::BeaconRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::BeaconRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::BeaconRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::BeaconRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::BeaconRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "556aa70db00b20ecb2bb8618209e1b41";
  }

  static const char* value(const ::robot::BeaconRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x556aa70db00b20ecULL;
  static const uint64_t static_value2 = 0xb2bb8618209e1b41ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::BeaconRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/BeaconRequest";
  }

  static const char* value(const ::robot::BeaconRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::BeaconRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_from_robot\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::robot::BeaconRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::BeaconRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_from_robot);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BeaconRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::BeaconRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::BeaconRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle_from_robot: ";
    Printer<float>::stream(s, indent + "  ", v.angle_from_robot);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_BEACONREQUEST_H
