// Generated by gencpp from file robot/Commands.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_COMMANDS_H
#define ROBOT_MESSAGE_COMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct Commands_
{
  typedef Commands_<ContainerAllocator> Type;

  Commands_()
    : commandOrder(0)
    , value(0.0)  {
    }
  Commands_(const ContainerAllocator& _alloc)
    : commandOrder(0)
    , value(0.0)  {
    }



   typedef int32_t _commandOrder_type;
  _commandOrder_type commandOrder;

   typedef float _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::robot::Commands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::Commands_<ContainerAllocator> const> ConstPtr;

}; // struct Commands_

typedef ::robot::Commands_<std::allocator<void> > Commands;

typedef boost::shared_ptr< ::robot::Commands > CommandsPtr;
typedef boost::shared_ptr< ::robot::Commands const> CommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::Commands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::Commands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::Commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::Commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::Commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::Commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::Commands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::Commands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eea913a9357e05e448c0c8f8d935dabb";
  }

  static const char* value(const ::robot::Commands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeea913a9357e05e4ULL;
  static const uint64_t static_value2 = 0x48c0c8f8d935dabbULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/Commands";
  }

  static const char* value(const ::robot::Commands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 commandOrder\n\
float32 value\n\
";
  }

  static const char* value(const ::robot::Commands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::Commands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.commandOrder);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Commands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::Commands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::Commands_<ContainerAllocator>& v)
  {
    s << indent << "commandOrder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.commandOrder);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_COMMANDS_H
