// Generated by gencpp from file robot/EncoderRequestResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_ENCODERREQUESTRESPONSE_H
#define ROBOT_MESSAGE_ENCODERREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct EncoderRequestResponse_
{
  typedef EncoderRequestResponse_<ContainerAllocator> Type;

  EncoderRequestResponse_()
    : leftCount(0)
    , rightCount(0)  {
    }
  EncoderRequestResponse_(const ContainerAllocator& _alloc)
    : leftCount(0)
    , rightCount(0)  {
    }



   typedef int64_t _leftCount_type;
  _leftCount_type leftCount;

   typedef int64_t _rightCount_type;
  _rightCount_type rightCount;




  typedef boost::shared_ptr< ::robot::EncoderRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::EncoderRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderRequestResponse_

typedef ::robot::EncoderRequestResponse_<std::allocator<void> > EncoderRequestResponse;

typedef boost::shared_ptr< ::robot::EncoderRequestResponse > EncoderRequestResponsePtr;
typedef boost::shared_ptr< ::robot::EncoderRequestResponse const> EncoderRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::EncoderRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::EncoderRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::EncoderRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::EncoderRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::EncoderRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::EncoderRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::EncoderRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::EncoderRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::EncoderRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da965117f83be82d823cfdc1c3990723";
  }

  static const char* value(const ::robot::EncoderRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda965117f83be82dULL;
  static const uint64_t static_value2 = 0x823cfdc1c3990723ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::EncoderRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/EncoderRequestResponse";
  }

  static const char* value(const ::robot::EncoderRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::EncoderRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 leftCount\n\
int64 rightCount\n\
\n\
";
  }

  static const char* value(const ::robot::EncoderRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::EncoderRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftCount);
      stream.next(m.rightCount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EncoderRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::EncoderRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::EncoderRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "leftCount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.leftCount);
    s << indent << "rightCount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.rightCount);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_ENCODERREQUESTRESPONSE_H
