// Generated by gencpp from file robot/LeftMotor.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_LEFTMOTOR_H
#define ROBOT_MESSAGE_LEFTMOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct LeftMotor_
{
  typedef LeftMotor_<ContainerAllocator> Type;

  LeftMotor_()
    : leftMotor(0.0)  {
    }
  LeftMotor_(const ContainerAllocator& _alloc)
    : leftMotor(0.0)  {
    }



   typedef float _leftMotor_type;
  _leftMotor_type leftMotor;




  typedef boost::shared_ptr< ::robot::LeftMotor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::LeftMotor_<ContainerAllocator> const> ConstPtr;

}; // struct LeftMotor_

typedef ::robot::LeftMotor_<std::allocator<void> > LeftMotor;

typedef boost::shared_ptr< ::robot::LeftMotor > LeftMotorPtr;
typedef boost::shared_ptr< ::robot::LeftMotor const> LeftMotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::LeftMotor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::LeftMotor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::LeftMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::LeftMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::LeftMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::LeftMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::LeftMotor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::LeftMotor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::LeftMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b05e1ef5e5f1a1141ed27c07178eedc";
  }

  static const char* value(const ::robot::LeftMotor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b05e1ef5e5f1a11ULL;
  static const uint64_t static_value2 = 0x41ed27c07178eedcULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::LeftMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/LeftMotor";
  }

  static const char* value(const ::robot::LeftMotor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::LeftMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 leftMotor\n\
";
  }

  static const char* value(const ::robot::LeftMotor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::LeftMotor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftMotor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LeftMotor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::LeftMotor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::LeftMotor_<ContainerAllocator>& v)
  {
    s << indent << "leftMotor: ";
    Printer<float>::stream(s, indent + "  ", v.leftMotor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_LEFTMOTOR_H
