// Generated by gencpp from file robot/RightMotor.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_RIGHTMOTOR_H
#define ROBOT_MESSAGE_RIGHTMOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct RightMotor_
{
  typedef RightMotor_<ContainerAllocator> Type;

  RightMotor_()
    : rightMotor(0.0)  {
    }
  RightMotor_(const ContainerAllocator& _alloc)
    : rightMotor(0.0)  {
    }



   typedef float _rightMotor_type;
  _rightMotor_type rightMotor;




  typedef boost::shared_ptr< ::robot::RightMotor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::RightMotor_<ContainerAllocator> const> ConstPtr;

}; // struct RightMotor_

typedef ::robot::RightMotor_<std::allocator<void> > RightMotor;

typedef boost::shared_ptr< ::robot::RightMotor > RightMotorPtr;
typedef boost::shared_ptr< ::robot::RightMotor const> RightMotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::RightMotor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::RightMotor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::RightMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::RightMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::RightMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::RightMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::RightMotor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::RightMotor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::RightMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d15360cc4f3d51c27ed554b188cb822";
  }

  static const char* value(const ::robot::RightMotor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d15360cc4f3d51cULL;
  static const uint64_t static_value2 = 0x27ed554b188cb822ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::RightMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/RightMotor";
  }

  static const char* value(const ::robot::RightMotor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::RightMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 rightMotor\n\
";
  }

  static const char* value(const ::robot::RightMotor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::RightMotor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rightMotor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RightMotor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::RightMotor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::RightMotor_<ContainerAllocator>& v)
  {
    s << indent << "rightMotor: ";
    Printer<float>::stream(s, indent + "  ", v.rightMotor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_RIGHTMOTOR_H
