// Generated by gencpp from file robot/TargetRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_TARGETREQUEST_H
#define ROBOT_MESSAGE_TARGETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct TargetRequest_
{
  typedef TargetRequest_<ContainerAllocator> Type;

  TargetRequest_()
    : angle_min(0.0)
    , angle_max(0.0)  {
    }
  TargetRequest_(const ContainerAllocator& _alloc)
    : angle_min(0.0)
    , angle_max(0.0)  {
    }



   typedef float _angle_min_type;
  _angle_min_type angle_min;

   typedef float _angle_max_type;
  _angle_max_type angle_max;




  typedef boost::shared_ptr< ::robot::TargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::TargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TargetRequest_

typedef ::robot::TargetRequest_<std::allocator<void> > TargetRequest;

typedef boost::shared_ptr< ::robot::TargetRequest > TargetRequestPtr;
typedef boost::shared_ptr< ::robot::TargetRequest const> TargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::TargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::TargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::TargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::TargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::TargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::TargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::TargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::TargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::TargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49e833ef41cffc32cbca68e3428713bf";
  }

  static const char* value(const ::robot::TargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49e833ef41cffc32ULL;
  static const uint64_t static_value2 = 0xcbca68e3428713bfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::TargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/TargetRequest";
  }

  static const char* value(const ::robot::TargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::TargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_min\n\
float32 angle_max\n\
";
  }

  static const char* value(const ::robot::TargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::TargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_min);
      stream.next(m.angle_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::TargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::TargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle_min: ";
    Printer<float>::stream(s, indent + "  ", v.angle_min);
    s << indent << "angle_max: ";
    Printer<float>::stream(s, indent + "  ", v.angle_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_TARGETREQUEST_H
