// Generated by gencpp from file robot/TargetResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_TARGETRESPONSE_H
#define ROBOT_MESSAGE_TARGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct TargetResponse_
{
  typedef TargetResponse_<ContainerAllocator> Type;

  TargetResponse_()
    : angle_from_target(0.0)
    , distance(0.0)
    , target_not_found(false)  {
    }
  TargetResponse_(const ContainerAllocator& _alloc)
    : angle_from_target(0.0)
    , distance(0.0)
    , target_not_found(false)  {
    }



   typedef float _angle_from_target_type;
  _angle_from_target_type angle_from_target;

   typedef float _distance_type;
  _distance_type distance;

   typedef uint8_t _target_not_found_type;
  _target_not_found_type target_not_found;




  typedef boost::shared_ptr< ::robot::TargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::TargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TargetResponse_

typedef ::robot::TargetResponse_<std::allocator<void> > TargetResponse;

typedef boost::shared_ptr< ::robot::TargetResponse > TargetResponsePtr;
typedef boost::shared_ptr< ::robot::TargetResponse const> TargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::TargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::TargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/buckeye/catkin_ws/src/CapstoneROS/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::TargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::TargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::TargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::TargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::TargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::TargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::TargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13f2edab508c01f49b1491e6283fff1b";
  }

  static const char* value(const ::robot::TargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13f2edab508c01f4ULL;
  static const uint64_t static_value2 = 0x9b1491e6283fff1bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::TargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/TargetResponse";
  }

  static const char* value(const ::robot::TargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::TargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_from_target \n\
float32 distance\n\
bool target_not_found\n\
";
  }

  static const char* value(const ::robot::TargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::TargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_from_target);
      stream.next(m.distance);
      stream.next(m.target_not_found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::TargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::TargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle_from_target: ";
    Printer<float>::stream(s, indent + "  ", v.angle_from_target);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "target_not_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_not_found);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_TARGETRESPONSE_H
