(cl:defpackage robot-msg
  (:use )
  (:export
   "<COMMANDS>"
   "COMMANDS"
   "<BEACONREQUEST>"
   "BEACONREQUEST"
   "<MOTORS>"
   "MOTORS"
   "<BEACONRESPONSE>"
   "BEACONRESPONSE"
   "<TARGETREQUEST>"
   "TARGETREQUEST"
   "<LEFTMOTOR>"
   "LEFTMOTOR"
   "<RIGHTMOTOR>"
   "RIGHTMOTOR"
   "<TARGETRESPONSE>"
   "TARGETRESPONSE"
   "<SAMPLEREQUEST>"
   "SAMPLEREQUEST"
   "<SAMPLERESPONSE>"
   "SAMPLERESPONSE"
  ))

